/*
 * This source file was generated by the Gradle 'init' task
 */
package com.kali.flink;

import com.kali.flink.event.EventLog;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        EventLog eventLog = new EventLog();
        eventLog.setEntryid("aaa");
        System.out.println(eventLog);
    }


}
